#!/usr/bin/env python3
"""Score frozen, locally trained models into the observation ledger only.

Use only artifacts generated by our ml_train job: joblib is executable pickle.
The manifest hash verifies an artifact's integrity, not an external author's trust.
No broker, watchlist, settings, or notification path is used here.
"""
from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import math
import sys
from datetime import UTC, date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import numpy as np  # noqa: E402

from quant.analyze import ml_scorer  # noqa: E402
from quant.analyze.ai_trader import append_judgments  # noqa: E402
from quant.control import selections  # noqa: E402
from quant.control.judgment import selection_attributes  # noqa: E402
from quant.core.models import Judgment, input_hash  # noqa: E402


def _load_model(model_dir: Path, market: str, session_date: str):
    stem = f"model_{market}_d1_return_bps"
    manifest = json.loads((model_dir / f"{stem}.manifest.json").read_text())
    if manifest.get("market") != market or manifest.get("target") != "d1_return_bps":
        raise ValueError("Model market/target does not match this shadow run")
    if date.fromisoformat(manifest["train_end"]) >= date.fromisoformat(session_date):
        raise ValueError("train_end must precede the prediction session date")
    available = manifest.get("training_labels_available_through")
    if available and date.fromisoformat(available) >= date.fromisoformat(session_date):
        raise ValueError("training label availability must precede prediction date")
    if manifest.get("feature_names") != list(ml_scorer.FEATURE_NAMES):
        raise ValueError("Model feature_names do not match the scorer")
    medians = np.asarray(manifest["imputation_medians"], dtype=float)
    if medians.shape != (len(ml_scorer.FEATURE_NAMES),) or not np.isfinite(medians).all():
        raise ValueError("Invalid training imputation_medians")
    path = model_dir / f"{stem}.joblib"
    if hashlib.sha256(path.read_bytes()).hexdigest() != manifest["model_sha256"]:
        raise ValueError("Model SHA-256 does not match the manifest")
    import joblib

    return joblib.load(path), manifest, medians


def _candidates(root: Path, market: str, session_date: str) -> list[dict]:
    rows, seen = [], set()
    for row in selections.load(root / "data/ledger/selections.jsonl"):
        if str(row.get("date")) != session_date or row.get("market") != market:
            continue
        if row.get("producer") not in (None, selections.WATCH_JOIN_PRODUCER):
            continue
        symbol = str(row.get("symbol") or "")
        if not symbol or symbol in seen:
            continue
        seen.add(symbol)
        rows.append(row)
    return rows


def _markdown(report: dict) -> str:
    lines = [f"# ML shadow — {report['session_date']} {report['market']}", "",
             "관찰용 D+1 수익률 예측. 주문·관심종목·자본 배분을 변경하지 않습니다.",
             "예측 bps는 비용 후 전략 손익이나 수익 보장이 아닙니다.", "",
             "과거 라벨의 가격 조정·지평 기준은 미검증입니다. 데이터 품질 진단용 관찰 실험입니다.", "",
             f"- 모델: `{report['model_sha256']}`",
             f"- 학습: {report['train_start']} ~ {report['train_end']}",
             f"- 검증 방식: {report['evaluation_protocol']}",
             f"- 후보 {len(report['predictions'])}개 / 규칙 점수 누락 {report['baseline_missing_count']}개",
             f"- 같은 규칙 점수 보유 후보 {report['comparison_candidates']}개에서 상위 5개 겹침: "
             f"{', '.join(report['overlap_symbols']) or '없음'}", "",
             "## ML 상위 5개", "", "| 종목 | 예측 D+1 bps | 후보 내 순위 점수 |",
             "| --- | ---: | ---: |"]
    for item in report["ml_top5"]:
        lines.append(f"| {item['symbol']} | {item['predicted_return_bps']:+.2f} | {item['percentile']:.1f} |")
    lines.extend(["", "## 규칙 점수 상위 5개", "", "| 종목 | 규칙 점수 |", "| --- | ---: |"])
    for item in report["baseline_top5"]:
        lines.append(f"| {item['symbol']} | {item['baseline_score100']:.2f} |")
    if not report["baseline_top5"]:
        lines.append("\n규칙 점수가 없어 비교할 수 없습니다.")
    return "\n".join(lines) + "\n"


def run_shadow(root: Path, model_dir: Path, market: str, session_date: str) -> dict:
    """Freeze model identity, reuse training medians, and append idempotent judgments."""
    if market not in ("KR", "US"):
        raise ValueError("market must be KR or US")
    model, manifest, medians = _load_model(model_dir, market, session_date)
    rows = _candidates(root, market, session_date)
    attrs = [selection_attributes(row) for row in rows]
    X = ml_scorer.fill_missing(ml_scorer.to_matrix(attrs), medians)
    if not np.isfinite(X).all():
        raise ValueError("Candidate features contain non-finite values")
    preds = np.asarray(model.predict(X), dtype=float) if rows else np.empty(0)
    if preds.shape != (len(rows),) or not np.isfinite(preds).all():
        raise ValueError("Model returned invalid predictions")
    percentiles = ml_scorer.to_percentile_scores(preds)
    bundle_hash = hashlib.sha256(json.dumps(manifest, sort_keys=True).encode()).hexdigest()
    version = bundle_hash[:12]
    now = datetime.now(UTC).isoformat(timespec="seconds")
    predictions, judgments = [], []
    for i, row in enumerate(rows):
        baseline = attrs[i].get("baseline_score100")
        baseline = float(baseline) if baseline is not None else None
        if baseline is not None and not math.isfinite(baseline):
            baseline = None
        predictions.append({
            "symbol": row["symbol"], "name": row.get("name"),
            "input_hash": input_hash(attrs[i]), "inputs": attrs[i],
            "features": {name: attrs[i].get(name) for name in ml_scorer.FEATURE_NAMES},
            "imputed_features": dict(zip(ml_scorer.FEATURE_NAMES, X[i].tolist())),
            "predicted_return_bps": float(preds[i]), "percentile": float(percentiles[i]),
            "baseline_score100": baseline,
        })
        judgments.append(Judgment(
            producer="ml_shadow", producer_version=version, input_hash=input_hash(attrs[i]),
            market=market, symbol=str(row["symbol"]), session_date=session_date,
            score=float(percentiles[i]), verdict="pass" if percentiles[i] >= 50 else "reject",
            rationale=f"Shadow D+1 expected return {preds[i]:+.2f} bps; observation only, not an order",
            ts=now,
        ))
    ml_top = sorted(predictions, key=lambda item: (-item["predicted_return_bps"], item["symbol"]))[:5]
    baseline_rows = [item for item in predictions if item["baseline_score100"] is not None]
    baseline_top = sorted(baseline_rows, key=lambda item: (-item["baseline_score100"], item["symbol"]))[:5]
    comparison_ml = sorted(baseline_rows, key=lambda item: (-item["predicted_return_bps"], item["symbol"]))[:5]
    report = {
        "producer": "ml_shadow", "producer_version": version, "mode": "shadow",
        "bundle_sha256": bundle_hash, "label_quality": "unverified_source_prices_and_horizons",
        "session_date": session_date, "market": market, "generated_at": now,
        "model_sha256": manifest["model_sha256"], "train_start": manifest["train_start"],
        "train_end": manifest["train_end"], "evaluation_protocol": manifest["evaluation_protocol"],
        "predictions": predictions, "ml_top5": ml_top, "baseline_top5": baseline_top,
        "comparison_ml_top5": comparison_ml, "comparison_candidates": len(baseline_rows),
        "baseline_missing_count": len(predictions) - len(baseline_rows),
        "overlap_symbols": sorted({item["symbol"] for item in comparison_ml} & {item["symbol"] for item in baseline_top}),
    }
    out = root / "data/ml_shadow"
    out.mkdir(parents=True, exist_ok=True)
    with (out / ".lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        if judgments:
            append_judgments(judgments, root / "data/ledger/judgments.jsonl")
        stem = f"{session_date}_{market}"
        (out / f"{stem}.json").write_text(json.dumps(report, ensure_ascii=False, indent=2, allow_nan=False) + "\n")
        (out / f"{stem}.md").write_text(_markdown(report))
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--market", choices=("KR", "US"), required=True)
    parser.add_argument("--date", default=datetime.now(ZoneInfo("Asia/Seoul")).date().isoformat())
    parser.add_argument("--model-dir", type=Path, required=True)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    args = parser.parse_args(argv)
    if args.date != datetime.now(ZoneInfo("Asia/Seoul")).date().isoformat():
        parser.error("Observation judgments can only be recorded for today's KST session")
    report = run_shadow(args.root, args.model_dir, args.market, args.date)
    print(f"ML shadow {args.date} {args.market}: {len(report['predictions'])} candidates; model={report['producer_version']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
